# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch]

jobs:
  # This workflow contains a single job called "greet"
  Import_VM_WS:
    # The type of runner that the job will run on
    runs-on: [self-hosted, windows, x64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Runs the deploy.ps1 script
    - name: Run deploy.ps1
      run: powershell -File Ansible/Deploy.ps1
