name: CI/CD with GitHub Actions

on: [workflow_dispatch]

jobs:
  Import_VM_WS:
    runs-on: [self-hosted, windows, x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run deploy.ps1
      run: powershell -File Ansible\win\Deploy.ps1

  # Import_VM_LN:
  #   runs-on: [self-hosted, windows, x64]

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Run deploy.ps1
  #     run: powershell -File Ansible\lin\Deploy.ps1
