name: Deploy VM

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy VM Script
      env:
        GITHUB_ESXIHOST: ${{ secrets.ESXIHOST }}
        GITHUB_ESXIUSERNAME: ${{ secrets.ESXIUSERNAME }}
        GITHUB_ESXIPASSWORD: ${{ secrets.ESXIPASSWORD }}
        GITHUB_VMNAME: ${{ secrets.VMNAMEW }}
        GITHUB_VMDATASTORE: ${{ secrets.VMDATASTORE }}
        GITHUB_FILENAME: ${{ secrets.FILENAMEW }}
        GITHUB_DISKFORMAT: ${{ secrets.DISKFORMAT }}
      run: |
        pwsh -File ./Deploy.ps1

  # Import_VM_LN:
  #   runs-on: [self-hosted, windows, x64]

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Run deploy.ps1
  #     run: powershell -File Ansible\lin\Deploy.ps1
