name: Deploy VM

on:
  workflow_dispatch:
  push:

jobs:
  Import_VM_WS:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy VM Script
        env:
          GITHUB_ESXIHOST: ${{ secrets.ESXIHOST }}
          GITHUB_ESXIUSERNAME: ${{ secrets.ESXIUSERNAME }}
          GITHUB_ESXIPASSWORD: ${{ secrets.ESXIPASSWORD }}
          GITHUB_VMNAME: ${{ secrets.VMNAMEW }}
          GITHUB_VMDATASTORE: ${{ secrets.VMDATASTORE }}
          GITHUB_FILENAME: ${{ secrets.FILENAMEW }}
          GITHUB_DISKFORMAT: ${{ secrets.DISKFORMAT }}
        run: powershell -File Ansible\win\Deploy.ps1

  Import_VM_LN:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy VM Script
        env:
          GITHUB_ESXIHOST: ${{ secrets.ESXIHOST }}
          GITHUB_ESXIUSERNAME: ${{ secrets.ESXIUSERNAME }}
          GITHUB_ESXIPASSWORD: ${{ secrets.ESXIPASSWORD }}
          GITHUB_VMNAME: ${{ secrets.VMNAMEL }}
          GITHUB_VMDATASTORE: ${{ secrets.VMDATASTORE }}
          GITHUB_FILENAME: ${{ secrets.FILENAMEL }}
          GITHUB_DISKFORMAT: ${{ secrets.DISKFORMAT }}
        run: powershell -File Ansible\lin\Deploy.ps1

  Test_VM_WS:
    runs-on: self-hosted
    needs: Import_VM_WS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy VM Script
        env:
          GITHUB_ESXIHOST: ${{ secrets.ESXIHOST }}
          GITHUB_ESXIUSERNAME: ${{ secrets.ESXIUSERNAME }}
          GITHUB_ESXIPASSWORD: ${{ secrets.ESXIPASSWORD }}
          GITHUB_VMNAME: ${{ secrets.VMNAMEW }}
          GITHUB_VMDATASTORE: ${{ secrets.VMDATASTORE }}
          GITHUB_FILENAME: ${{ secrets.FILENAMEW }}
          GITHUB_DISKFORMAT: ${{ secrets.DISKFORMAT }}
          GITHUB_DISK: ${{ secrets.DISK_W }}
          GITHUB_CPU: ${{ secrets.CPU_W }}
          GITHUB_MEMORY: ${{ secrets.MEMORY_W }}
        run: powershell -File Ansible\win\Configuration_W.ps1

  Test_VM_LN:
    runs-on: self-hosted
    needs: Test_VM_LS
    steps:
      - name: Deploy VM Script
        env:
          GITHUB_ESXIHOST: ${{ secrets.ESXIHOST }}
          GITHUB_ESXIUSERNAME: ${{ secrets.ESXIUSERNAME }}
          GITHUB_ESXIPASSWORD: ${{ secrets.ESXIPASSWORD }}
          GITHUB_VMNAME: ${{ secrets.VMNAMEL }}
          GITHUB_VMDATASTORE: ${{ secrets.VMDATASTORE }}
          GITHUB_FILENAME: ${{ secrets.FILENAMEL }}
          GITHUB_DISKFORMAT: ${{ secrets.DISKFORMAT }}
          GITHUB_DISK: ${{ secrets.DISK_L }}
          GITHUB_CPU: ${{ secrets.CPU_L }}
          GITHUB_MEMORY: ${{ secrets.MEMORY_L }}
        run: powershell -File Ansible\lin\Configuration_L.ps1
