name: Deploy VM

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: [self-hosted, windows, x64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy VM Script
      run: |
        echo "ESXIHOST: ${{ env.ESXIHOST }}"
        echo "ESXIUSERNAME: ${{ env.ESXIUSERNAME }}"
        echo "ESXIPASSWORD: ${{ env.ESXIPASSWORD }}"
        echo "VMNAME: ${{ env.VMNAME }}"
        echo "VMDATASTORE: ${{ env.VMDATASTORE }}"
        echo "FILENAME: ${{ env.FILENAME }}"
        echo "DISKFORMAT: ${{ env.DISKFORMAT }}"
        echo "DISKFORMAT: ${{ vars.DISKFORMAT }}"
      env:
        GITHUB_ESXIHOST: ${{ env.ESXIHOST }}
        GITHUB_ESXIUSERNAME: ${{ env.ESXIUSERNAME }}
        GITHUB_ESXIPASSWORD: ${{ env.ESXIPASSWORD }}
        GITHUB_VMNAME: ${{ env.VMNAMEW }}
        GITHUB_VMDATASTORE: ${{ env.VMDATASTORE }}
        GITHUB_FILENAME: ${{ env.FILENAMEW }}
        GITHUB_DISKFORMAT: ${{ env.DISKFORMAT }}
      # run: powershell -File Ansible\win\Deploy.ps1

  # Import_VM_LN:
  #   runs-on: [self-hosted, windows, x64]

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Run deploy.ps1
  #     run: powershell -File Ansible\lin\Deploy.ps1
