name: Deploy VM

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: [self-hosted, windows, x64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy VM Script
      env:
        GITHUB_ESXIHOST: ${{ vars.ESXIHOST }}
        GITHUB_ESXIUSERNAME: ${{ vars.ESXIUSERNAME }}
        GITHUB_ESXIPASSWORD: ${{ vars.ESXIPASSWORD }}
        GITHUB_VMNAME: ${{ vars.VMNAMEW }}
        GITHUB_VMDATASTORE: ${{ vars.VMDATASTORE }}
        GITHUB_FILENAME: ${{ vars.FILENAMEW }}
        GITHUB_DISKFORMAT: ${{ vars.DISKFORMAT }}
      run: powershell -File Ansible\win\Deploy.ps1

  # Import_VM_LN:
  #   runs-on: [self-hosted, windows, x64]

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Run deploy.ps1
  #     run: powershell -File Ansible\lin\Deploy.ps1
